package job

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-swagger/go-swagger/httpkit"

	"github.com/IcelandairLabs/micro.jenkins/models"
)

/*GetJobListOK OK

swagger:response getJobListOK
*/
type GetJobListOK struct {

	// In: body
	Payload []*models.Job `json:"body,omitempty"`
}

// NewGetJobListOK creates GetJobListOK with default headers values
func NewGetJobListOK() *GetJobListOK {
	return &GetJobListOK{}
}

// WithPayload adds the payload to the get job list o k response
func (o *GetJobListOK) WithPayload(payload []*models.Job) *GetJobListOK {
	o.Payload = payload
	return o
}

// WriteResponse to the client
func (o *GetJobListOK) WriteResponse(rw http.ResponseWriter, producer httpkit.Producer) {

	rw.WriteHeader(200)
	if err := producer.Produce(rw, o.Payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}
