package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*health Health health

swagger:model health
*/
type Health struct {

	/* Error error
	 */
	Error *int64 `json:"error,omitempty"`

	/* Status status
	 */
	Status *int64 `json:"status,omitempty"`
}

// Validate validates this health
func (m *Health) Validate(formats strfmt.Registry) error {
	return nil
}
