package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*Job Job job

swagger:model Job
*/
type Job struct {

	/* Color color
	 */
	Color *string `json:"color,omitempty"`

	/* Name name
	 */
	Name *string `json:"name,omitempty"`

	/* URL url
	 */
	URL *string `json:"url,omitempty"`
}

// Validate validates this job
func (m *Job) Validate(formats strfmt.Registry) error {
	return nil
}
